# Azure DevOps Pipeline using a self-hosted agent
trigger:
- main  # Run the pipeline on commits to the 'main' branch

# Use self-hosted agent
pool:
  name: 'Azure Pipelines'  # Use the agent pool name where the self-hosted agent is registered

steps:
- script: echo "Starting the build on a self-hosted agent..."
  displayName: 'Echo Start'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build'

- script: |
    npm test
  displayName: 'Run Tests'

- script: echo "Pipeline completed successfully!"
  displayName: 'Echo Done'
